# Generated by Django 5.0.6 on 2024-05-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
