# Generated by Django 5.0.6 on 2024-05-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comment_raiting_alter_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
    ]
